version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - pytest

